### ISSUE TITLE
ics import fails

### ISSUE THREAD

**Issue by frase-git** [cmb69/calendar_xh#47] opened 2021-04-13 07:53 UTC
First: Many thanks for version 2.0

Unfortunately, attempts to import complex ics files failed with the following message (white page):

> Uncaught TypeError: Argument 1 passed to Calendar\Event::create() must be of the type string, null given, called in \plugins\calendar\classes\ICalendarReader.php on line 95 and defined in \plugins\calendar\classes\Event.php:72
> Stack trace:
> #0 \plugins\calendar\classes\ICalendarReader.php(95): Calendar\Event::create(NULL, NULL, NULL, NULL, 'Neujahr in Deut...', '', '', NULL)
> #1 \plugins\calendar\classes\ICalendarReader.php(58): Calendar\ICalendarReader->parse()
> #2 \plugins\calendar\classes\IcalImportController.php(82): Calendar\ICalendarReader->read()
> #3 \plugins\calendar\classes\Plugin.php(129): Calendar\IcalImportController->importAction()
> #4 \plugins\calendar\classes\Event.php on line 72

With simpler files, however, the import works without problems.

(Example of a complex failed file:
https://www.ferienwiki.de/exports/de -> "Feiertage gesamt"

**Comment by cmb69** [comment] 2021-04-13 22:21
> Many thanks for version 2.0

Actually, I'm happy to have it released after such a long time, and I think it's better (at least internally) than I had hoped – still, far from good.

Many thanks for checking it and filing bug reports! :)

> Unfortunately, attempts to import complex ics files failed with the following message (white page):

Confirmed. This is actually a duplicate of #19. For a quick workaround see https://cmsimpleforum.com/viewtopic.php?f=16&t=13290#p64837. I'll try to address this soonish, since being able to import these files makes a whole lot of sense. And at the very least, the import shouldn't produce a WSOD.

**Comment by cmb69** [comment] 2021-05-01 12:45
Re-opening, to distinguish this bug from the enhancement of #19.

**Closed** 2021-05-01 12:58 UTC
Labels: bug
